AL = ["BC", "NW", "SA"]
ON = ["MA", "QU"]
MA = ["SA", "NU", "ON"]
SA = ["NW", "AL", "MA"]
BC = ["YK", "NW", "AL"]
NS = ["PE", "NB"]
NF = ["QU"]
NW = ["YK", "BC", "AL", "SA", "NU"]
NU = ["NW", "QU", "MA"]
QU = ["NU", "ON", "NF", "NB"]
NB = ["QU", "PE", "NS"]
PE = ["NB", "NS"]
YK = ["BC", "NW"]
