TX = [ "LA", "AR", "OK", "NM" ]
AL = ["FL", "GA", "TN", "MS"]
AR = ["MO", "TN", "MS", "LA", "TX", "OK"]
AZ = ["NM", "UT", "NV", "CA"]
CA = ["OR", "NV", "AZ"]
CO = ["WY", "UT", "NM", "OK", "KS", "NE"]
CT = ["NY", "MA", "RI"]
DE = ["NJ", "PA", "MD"]
FL = ["GA", "AL"]
GA = ["SC", "NC", "TN", "AL", "FL"]
IA = ["MO", "IL", "WI", "MN", "SD", "NE"]
ID = ["WA", "OR", "NV", "UT", "WY", "MT"]
IL = ["IA", "WI", "MO", "KY", "IN"]
IN = ["MI", "OH", "KY", "IL"]
KS = ["CO", "OK", "MO", "NE"]
KY = ["TN", "VA", "WV", "OH", "IN", "IL", "MO"]
LA = ["MS", "AR", "OK", "TX"]
MA = ["NH", "VT", "NY", "RI", "CT"]
MD = ["DE", "PA", "WV", "VA"]
ME = ["NH"]
MI = ["OH", "IN", "WI"]
MN = ["WI", "ND", "SD", "IA"]
MO = ["IA", "IL", "NE", "KS", "OK", "AR", "TN", "KY"]
MS = ["LA", "AR", "TN", "AL"]
MT = ["ID", "WY", "ND", "SD"]
NC = ["VA", "TN", "GA", "SC"]
ND = ["SD", "MN", "MT"]
NE = ["WY", "CO", "KS", "MO", "IA", "SD"]
NH = ["ME", "MA", "VT"]
NJ = ["NY", "PA", "DE"]
NM = ["AZ", "CO", "OK", "TX"]
NV = ["CA", "OR", "ID", "UT", "AZ"]
NY = ["VT", "MA", "CT", "NJ", "PA"]
OH = ["WV", "PA", "MI", "IN", "KY"]
OK = ["TX", "LA", "AR", "MO", "KS", "CO", "NM"]
OR = ["WA", "ID", "NV", "CA"]
PA = ["NY", "NJ", "DE", "MD", "WV", "OH"]
RI = ["MA", "CT"]
SC = ["NC", "GA"]
SD = ["ND", "MT", "WY", "NE", "IA", "MN"]
TN = ["MS", "AL", "GA", "NC", "VA", "KY", "MO", "AR"]
UT = ["NV", "AZ", "CO", "WY", "ID"]
VA = ["MD", "WV", "KY", "TN", "NC"]
VT = ["NH", "MA", "NY"]
WA = ["ID", "OR"]
WI = ["MN", "IA", "IL", "MI"]
WV = ["VA", "MD", "PA", "OH", "KY"]
WY = ["MT", "ID", "UT", "CO", "NE", "SD"]
